language: python

cache: pip

python:
    - "3.6"
    - "3.6-dev"
    - "nightly"

install:
    - pip install coveralls codecov
    - pip install .

script:
    - odfcleaner -h
    - nosetests --with-coverage --cover-package=odfcleaner -d

after_success:
    - codecov
    - coveralls
